version: 2
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers-legacy
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
      - image: postgres:11.4
        environment:
          POSTGRES_USER: whether_sweater
          POSTGRES_DB: whether_sweater_test
          POSTGRES_PASSWORD: password

    steps:
      - checkout

       # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-r-{{ checksum "Gemfile.lock" }}-y-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Which version of bundler?
      - run:
          name: update bundler version
          command: gem install bundler:2.0.1

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: install dependencies
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
            - ~/.cache
          key: v1-dependencies-r-{{ checksum "Gemfile.lock" }}-y-{{ checksum "yarn.lock" }}
        
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: bundle exec rails db:create db:migrate

      # Analyze source code & clean code
      - run:
          name: run linting
          command: |
            bundle exec rubocop
      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            COVERAGE=true bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress
                            